# Generated by Django 5.1.2 on 2024-11-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-username']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscribers_count',
        ),
        migrations.RemoveField(
            model_name='video',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='video',
            name='likes',
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(default='AnonymUser.png', upload_to='channel_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='AnonymUser', max_length=150, unique=True),
        ),
    ]
