# Generated by Django 5.1.2 on 2024-11-28 14:56

import vlog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0002_alter_user_options_remove_user_subscribers_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='comments',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(default='channel_images/AnonymUser.png', upload_to='channel_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=vlog.models.generate_unique_name, max_length=150, unique=True),
        ),
    ]
