services:
    django:
        build: .
        working_dir: /app/clip_joy
        command: sh -c "gunicorn --bind unix:/run/gunicorn.sock myvlog.wsgi:application && chmod 0777 /run/gunicorn.sock"
        volumes:
            - ./clip_joy:/clip_joy
            - static:/app/clip_joy/static
            - media_files:/app/clip_joy/media
            - gunicorn_socket:/run

        ports:
            - "8000:8000"

        environment:
            #
            #
            #
            #

        depends_on:
            - db

    db:
        image: postgres:13-alpine
        volumes:
            - pg_data:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: 'clip_joy'
            POSTGRES_USER: 'django_admin'
            POSTGRES_PASSWORD: 'admin'

    nginx:
        image: nginx:1.19.8-alpine
        depends_on:
            - django
        ports:
            - "80:80"
        volumes:
            - static:/clip_joy/static
            - media_files:/clip_joy/media
            - ./nginx-conf.d:/etc/nginx/conf.d
            - gunicorn_socket:/run

volumes:
    pg_data:
    static:
    media_files:
    gunicorn_socket:
